-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements


- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: 1.0.4
  hooks:
  - id: python-import-sorter
    args: ['--silent-overwrite']
    exclude: migrations|settings


-   repo: https://github.com/pre-commit/mirrors-autopep8
    sha: HEAD  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8